---
- name: ECS create new S3 bucket
  hosts: localhost
  gather_facts: False
  vars:
    username: <ENTER YOUR USERNAME>
    password: <ENTER YOUR PASSWORD>
    ECS_host: <ENTER ECS IP/HOSTNAME>
    BucketName: mybucket
    NameSpace: ns1

  tasks:

  - name: Get ECS API authentication token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      url: https://{{ECS_host}}:4443/login
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      return_content: yes
    register: results_login
    no_log: True

  - name: Connect to ECS using a previously stored cookie to create new buckets
    uri:
      validate_certs: no
      url: https://{{ECS_host}}:4443/object/bucket.json
      method: POST
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      body_format: json
      body:
        {
          "name": "{{ BucketName}}",
          "filesystem_enabled": "false",
          "head_type": "s3",
          "namespace": "{{NameSpace}}",
          "retention": "3",
          "is_stale_allowed": "false",
          "search_metadata": [
            {
              "name": "x-amz-meta-custom-type",
              "datatype": "integer"
            } ]
        }
      return_content: yes
    register: results_CreateBucket

  - debug:
     msg="{{ results_CreateBucket }}"
